export const recipes = [
  {
    slug: "beginners-sourdough-bread",
    title: "Beginner's Sourdough Bread",
    category: "Baking",
    image: "https://images.unsplash.com/photo-1585478259715-876acc5be8eb?w=800&h=600&fit=crop",
    description: "A step-by-step guide to baking your first sourdough loaf with a crispy crust and soft, tangy interior.",
    time: "2 days",
    yield: "1 loaf",
    difficulty: "Intermediate",
    featured: true,
    ingredients: {
      starter: [
        { item: "Sourdough starter", amount: "30g" },
        { item: "Bread flour", amount: "60g" },
        { item: "Water (78°F / 26°C)", amount: "60g" },
      ],
      dough: [
        { item: "Ripe sourdough starter", amount: "100g" },
        { item: "Water (78°F / 26°C)", amount: "350g" },
        { item: "Bread flour", amount: "500g" },
        { item: "Whole wheat flour", amount: "50g" },
        { item: "Salt", amount: "10g" },
      ],
    },
    instructions: [
      "Feed your starter 4-8 hours before mixing the dough. Use it when it's at peak rise.",
      "In a large bowl, mix the water and ripe starter until milky. Add flours and mix until no dry spots remain. Rest 30 minutes (autolyse).",
      "Add salt and perform stretch and folds — grab the dough from underneath, stretch up, and fold over. Repeat 4 times, rotating the bowl. Do this every 30 minutes for 2 hours.",
      "Cover and let bulk ferment at 78°F for 4-6 hours until the dough has risen 50-75% and shows bubbles on the surface.",
      "Turn dough onto a lightly floured surface. Shape into a round boule using the pull-and-tuck method. Place seam-side up in a floured banneton.",
      "Cover and refrigerate overnight (12-16 hours) for cold retard.",
      "Preheat oven to 500°F with a Dutch oven inside for 45 minutes. Score the dough with a lame, place in the hot Dutch oven, cover, and bake 20 minutes. Remove lid, reduce to 450°F, and bake another 20-25 minutes until deep golden.",
      "Cool on a wire rack for at least 1 hour before slicing.",
    ],
    tips: [
      "Temperature matters — 78°F is ideal for fermentation. Use a folding proofer if your kitchen is too cold.",
      "A banneton helps the dough hold its shape during the final proof.",
      "Don't worry if your first loaf isn't perfect. Every bake teaches you something new.",
    ],
  },
  {
    slug: "honey-wheat-sandwich-bread",
    title: "Honey Wheat Sandwich Bread",
    category: "Baking",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&h=600&fit=crop",
    description: "Soft, fluffy sandwich bread with a touch of honey and whole wheat flavor. Perfect for everyday use.",
    time: "3 hours",
    yield: "1 loaf",
    difficulty: "Beginner",
    featured: false,
    ingredients: {
      dough: [
        { item: "Warm water (110°F)", amount: "1 cup" },
        { item: "Active dry yeast", amount: "2¼ tsp" },
        { item: "Honey", amount: "¼ cup" },
        { item: "Whole wheat flour", amount: "1½ cups" },
        { item: "Bread flour", amount: "1½ cups" },
        { item: "Butter, softened", amount: "3 tbsp" },
        { item: "Salt", amount: "1½ tsp" },
      ],
    },
    instructions: [
      "Dissolve honey in warm water, sprinkle yeast on top. Let stand 5-10 minutes until foamy.",
      "In a large bowl, combine whole wheat flour and bread flour. Add yeast mixture, softened butter, and salt.",
      "Knead by hand 8-10 minutes or with a stand mixer on medium-low for 6-7 minutes until smooth and elastic.",
      "Place in a greased bowl, cover, and let rise in a warm spot for 1-1.5 hours until doubled.",
      "Punch down, shape into a loaf, and place in a greased 9x5 inch loaf pan.",
      "Cover and let rise 45-60 minutes until the dough rises about 1 inch above the pan edge.",
      "Bake at 350°F for 30-35 minutes until golden brown and the internal temperature reaches 190°F.",
      "Remove from pan and cool on a wire rack before slicing.",
    ],
    tips: [
      "For a softer crust, brush the top with melted butter immediately after removing from the oven.",
      "This bread stays fresh for 3-4 days stored in an airtight bag at room temperature.",
    ],
  },
  {
    slug: "rustic-focaccia",
    title: "Rustic Olive Oil Focaccia",
    category: "Baking",
    image: "https://images.unsplash.com/photo-1549931319-a545753467c8?w=800&h=600&fit=crop",
    description: "Crispy, golden focaccia loaded with olive oil, flaky sea salt, and fresh rosemary.",
    time: "2 hours",
    yield: "1 sheet pan",
    difficulty: "Beginner",
    featured: false,
    ingredients: {
      dough: [
        { item: "Bread flour", amount: "4 cups" },
        { item: "Warm water", amount: "1¾ cups" },
        { item: "Instant yeast", amount: "2¼ tsp" },
        { item: "Olive oil", amount: "¼ cup + more for drizzling" },
        { item: "Salt", amount: "2 tsp" },
        { item: "Flaky sea salt", amount: "for topping" },
        { item: "Fresh rosemary", amount: "for topping" },
      ],
    },
    instructions: [
      "Combine warm water, yeast, and a pinch of sugar. Let sit 5 minutes until bubbly.",
      "Mix flour and salt in a large bowl. Add yeast mixture and olive oil. Stir until a shaggy dough forms.",
      "Cover and let rise 1 hour. Fold the dough over itself 4 times in the bowl, then let rise another 30 minutes.",
      "Generously oil a sheet pan. Transfer dough and gently stretch to fill the pan. If it springs back, wait 10 minutes and try again.",
      "Cover and let rise 30-45 minutes until puffy.",
      "Preheat oven to 425°F. Dimple the surface with oiled fingers, drizzle generously with olive oil, and scatter rosemary and flaky salt.",
      "Bake 22-25 minutes until deep golden brown on top and crispy on the bottom.",
      "Cool 5 minutes in the pan, then transfer to a wire rack. Serve warm.",
    ],
    tips: [
      "Use high-quality extra virgin olive oil — it makes a huge difference in flavor.",
      "For the best texture, let the dough cold-ferment in the fridge overnight before baking.",
    ],
  },
  {
    slug: "chocolate-chip-cookies",
    title: "Perfect Chocolate Chip Cookies",
    category: "Dessert",
    image: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800&h=600&fit=crop",
    description: "Chewy in the center, crispy on the edges, loaded with melty chocolate chips.",
    time: "45 min",
    yield: "36 cookies",
    difficulty: "Beginner",
    featured: false,
    ingredients: {
      dough: [
        { item: "All-purpose flour", amount: "2¼ cups" },
        { item: "Butter, softened", amount: "1 cup" },
        { item: "Granulated sugar", amount: "¾ cup" },
        { item: "Brown sugar, packed", amount: "¾ cup" },
        { item: "Vanilla extract", amount: "2 tsp" },
        { item: "Eggs", amount: "2 large" },
        { item: "Baking soda", amount: "1 tsp" },
        { item: "Salt", amount: "1 tsp" },
        { item: "Chocolate chips", amount: "2 cups" },
      ],
    },
    instructions: [
      "Preheat oven to 375°F. Line baking sheets with parchment paper.",
      "Whisk flour, baking soda, and salt in a bowl. Set aside.",
      "Beat softened butter with both sugars until light and fluffy, about 3 minutes. Beat in eggs one at a time, then add vanilla.",
      "Gradually mix in the flour mixture on low speed until just combined. Fold in chocolate chips.",
      "Scoop rounded tablespoons of dough onto prepared baking sheets, spacing 2 inches apart.",
      "Bake 10-12 minutes until edges are golden but centers still look slightly underdone.",
      "Let cool on baking sheet 5 minutes, then transfer to a wire rack.",
    ],
    tips: [
      "Chill the dough for 30 minutes for thicker, chewier cookies.",
      "Use a mix of chocolate chips and chopped chocolate bars for varied texture.",
    ],
  },
  {
    slug: "sourdough-pizza-dough",
    title: "Sourdough Pizza Dough",
    category: "Lunch & Dinner",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&h=600&fit=crop",
    description: "Thin, crispy sourdough pizza crust with beautiful char and tangy flavor.",
    time: "24 hours",
    yield: "4 pizzas",
    difficulty: "Intermediate",
    featured: false,
    ingredients: {
      dough: [
        { item: "Sourdough starter, ripe", amount: "100g" },
        { item: "Water (80°F)", amount: "325g" },
        { item: "Bread flour", amount: "500g" },
        { item: "Olive oil", amount: "15g" },
        { item: "Salt", amount: "10g" },
      ],
    },
    instructions: [
      "Mix starter, water, and flour until combined. Autolyse for 30 minutes.",
      "Add salt and olive oil. Mix thoroughly, then perform 3 sets of stretch and folds 30 minutes apart.",
      "Cover and bulk ferment at room temperature for 4-6 hours.",
      "Divide into 4 equal balls (about 220g each). Shape into tight rounds.",
      "Place in oiled containers and refrigerate for at least 12 hours (up to 48 hours for more flavor).",
      "Remove from fridge 2 hours before baking. Let come to room temperature.",
      "Preheat oven to 550°F with a pizza stone or steel for 45 minutes.",
      "Stretch dough gently into 12-inch rounds. Top with sauce, cheese, and desired toppings.",
      "Bake 8-10 minutes until crust is charred and cheese is bubbly.",
    ],
    tips: [
      "The longer the cold ferment, the more complex the flavor.",
      "Use a bench scraper to help handle the dough without deflating it.",
    ],
  },
  {
    slug: "banana-bread",
    title: "Classic Banana Bread",
    category: "Dessert",
    image: "https://images.unsplash.com/photo-1605090930601-4f878f570887?w=800&h=600&fit=crop",
    description: "Moist, tender banana bread with caramelized banana flavor. A timeless classic.",
    time: "1 hour",
    yield: "1 loaf",
    difficulty: "Beginner",
    featured: false,
    ingredients: {
      dough: [
        { item: "Ripe bananas, mashed", amount: "3 large" },
        { item: "Butter, melted", amount: "⅓ cup" },
        { item: "Sugar", amount: "¾ cup" },
        { item: "Egg", amount: "1 large" },
        { item: "Vanilla extract", amount: "1 tsp" },
        { item: "All-purpose flour", amount: "1½ cups" },
        { item: "Baking soda", amount: "1 tsp" },
        { item: "Salt", amount: "¼ tsp" },
      ],
    },
    instructions: [
      "Preheat oven to 350°F. Grease a 9x5 inch loaf pan.",
      "Mash bananas in a large bowl. Mix in melted butter.",
      "Stir in sugar, egg, and vanilla extract.",
      "Sprinkle baking soda and salt over the mixture, then gently fold in flour until just combined.",
      "Pour batter into prepared pan.",
      "Bake 55-65 minutes until a toothpick inserted in the center comes out clean.",
      "Cool in pan 10 minutes, then transfer to a wire rack.",
    ],
    tips: [
      "Use very ripe bananas with brown spots for the best sweetness and flavor.",
      "Add walnuts or chocolate chips for extra texture.",
    ],
  },
];
